import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Search, Database, Brain, GitBranch, Zap, ChevronRight } from 'lucide-react';
import { Button } from '../components/common';

const domains = [
  { id: 'energy', label: 'Energy', color: 'from-amber-500 to-orange-500' },
  { id: 'traffic', label: 'Traffic', color: 'from-blue-500 to-cyan-500' },
  { id: 'sales', label: 'Sales', color: 'from-emerald-500 to-teal-500' },
  { id: 'finance', label: 'Finance', color: 'from-purple-500 to-pink-500' },
  { id: 'iot', label: 'IoT', color: 'from-indigo-500 to-violet-500' },
];

const features = [
  {
    icon: Database,
    title: 'Dataset Discovery',
    description: 'Semantic search across curated time-series datasets. Find energy, traffic, sales, and financial data with intelligent relevance scoring.',
    color: 'from-indigo-500 to-blue-500',
  },
  {
    icon: Brain,
    title: 'Automated EDA',
    description: 'Automatic exploratory data analysis with key statistics, column profiling, and correlation insights generated by AI.',
    color: 'from-cyan-500 to-teal-500',
  },
  {
    icon: GitBranch,
    title: 'Adaptive ML Pipelines',
    description: 'Visual pipeline builder with automated model selection, hyperparameter tuning, and continuous learning capabilities.',
    color: 'from-pink-500 to-rose-500',
  },
];

export function Home() {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState('');

  const handleSearch = (query: string) => {
    navigate(`/discover?q=${encodeURIComponent(query)}`);
  };

  const handleDomainClick = (domain: string) => {
    navigate(`/discover?q=${encodeURIComponent(domain)}`);
  };

  return (
    <div className="min-h-[calc(100vh-4rem)] flex flex-col">
      {/* Hero Section */}
      <section className="flex-1 flex items-center justify-center px-6 py-20 relative overflow-hidden">
        {/* Background Effects */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-indigo-500/20 rounded-full blur-3xl animate-pulse" />
          <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-cyan-500/20 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '1s' }} />
          <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PHBhdHRlcm4gaWQ9ImdyaWQiIHdpZHRoPSI2MCIgaGVpZ2h0PSI2MCIgcGF0dGVyblVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHBhdGggZD0iTSA2MCAwIEwgMCAwIDAgNjAiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzJkMzM0NCIgc3Ryb2tlLXdpZHRoPSIxIi8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ1cmwoI2dyaWQpIi8+PC9zdmc+')] opacity-30" />
        </div>

        <div className="max-w-4xl mx-auto text-center relative z-10">
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-space-800/80 border border-space-600 mb-8"
          >
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
            </span>
            <span className="text-sm text-slate-300">Autonomous Time-Series Intelligence</span>
          </motion.div>

          {/* Title */}
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-5xl md:text-6xl font-bold mb-6"
          >
            <span className="gradient-text">Intelligent Forecasting</span>
            <br />
            <span className="text-white">Powered by AI</span>
          </motion.h1>

          {/* Subtitle */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="text-lg text-slate-400 mb-10 max-w-2xl mx-auto"
          >
            Transform raw time-series data into actionable forecasts with automated machine learning pipelines.
            Discover datasets, analyze patterns, and deploy production-ready models in minutes.
          </motion.p>

          {/* Search Bar */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="max-w-2xl mx-auto mb-8"
          >
            <div className="relative group">
              <div className="absolute -inset-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-cyan-500 rounded-xl blur-lg opacity-30 group-hover:opacity-50 transition-opacity duration-300" />
              <div className="relative flex items-center bg-space-800 border border-space-600 rounded-xl overflow-hidden">
                <Search className="absolute left-4 w-5 h-5 text-slate-500" />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSearch(searchQuery)}
                  placeholder="Search datasets: energy, traffic, sales, finance..."
                  className="w-full bg-transparent text-white placeholder-slate-500 px-12 py-4 focus:outline-none text-lg"
                />
                <Button
                  onClick={() => handleSearch(searchQuery)}
                  className="mr-2"
                >
                  Search
                </Button>
              </div>
            </div>
          </motion.div>

          {/* Domain Chips */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.4 }}
            className="flex flex-wrap items-center justify-center gap-3"
          >
            <span className="text-sm text-slate-500">Quick search:</span>
            {domains.map((domain) => (
              <button
                key={domain.id}
                onClick={() => handleDomainClick(domain.id)}
                className={`
                  px-4 py-1.5 rounded-full text-sm font-medium text-white
                  bg-gradient-to-r ${domain.color} bg-opacity-10 border border-opacity-30
                  hover:bg-opacity-20 transition-all duration-200
                  flex items-center gap-2
                `}
                style={{ borderColor: 'currentColor', borderWidth: 1, borderStyle: 'solid' }}
              >
                {domain.label}
                <ChevronRight className="w-3 h-3 opacity-50" />
              </button>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="px-6 py-20 bg-space-800/50">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-white mb-4">
              Built for Time-Series Intelligence
            </h2>
            <p className="text-slate-400 max-w-2xl mx-auto">
              Our platform combines state-of-the-art ML techniques with an intuitive interface
              to accelerate your time-series forecasting projects.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                whileHover={{ y: -5 }}
                className="group p-6 bg-space-800 border border-space-600 rounded-xl hover:border-space-500 transition-all duration-300"
              >
                <div className={`inline-flex p-3 rounded-xl bg-gradient-to-br ${feature.color}`}>
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="mt-4 text-xl font-semibold text-white">{feature.title}</h3>
                <p className="mt-2 text-sm text-slate-400 leading-relaxed">
                  {feature.description}
                </p>
                <div className="mt-4 flex items-center gap-2 text-indigo-400 text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity">
                  Learn more <ChevronRight className="w-4 h-4" />
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="px-6 py-16">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="p-8 rounded-2xl bg-gradient-to-br from-indigo-500/10 to-cyan-500/10 border border-indigo-500/20"
          >
            <Zap className="w-12 h-12 text-indigo-400 mx-auto mb-4" />
            <h3 className="text-2xl font-bold text-white mb-2">
              Ready to transform your data?
            </h3>
            <p className="text-slate-400 mb-6">
              Start exploring datasets or build your first forecasting pipeline today.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4">
              <Button onClick={() => navigate('/discover')}>
                Explore Datasets
              </Button>
              <Button variant="secondary" onClick={() => navigate('/pipeline')}>
                View Pipeline Studio
              </Button>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
